---
- name: Deploy Application Containers (Redis, Nginx)
  hosts: infra, app
  become: true
  tasks:
  
    - name: Run Redis container
      community.docker.docker_container:
        name: redis
        image: redis:latest
        state: started
        restart_policy: always
        ports:
          - "6379:6379"
  
    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
