global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  

  - job_name: "infra"
    static_configs:
      - targets: ["34.225.92.19:9100"] 

  - job_name: "app"
    static_configs:
      - targets: ["18.214.122.235:9100"] 

rule_files:
  - "/opt/prometheus/alert.rules.yml"
